services:

  db:
    image: couchbase:community-7.1.1
    restart: always
    volumes:
      - ./data/couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8093-8096:8093-8096
      - 11210-11211:11210-11211
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8091"]
        interval: 30s
        timeout: 10s
        retries: 5